version: "{build}"
image: Visual Studio 2019

# Source Config
clone_folder: c:\gopath\src\github.com\pact-foundation\pact-go

init:
  - git config --global core.autocrlf input

install:
  - go version
  - go env

build: false
deploy: false

test_script:
  - go build -o /tmp/pact-go github.com/pact-foundation/pact-go
  - ps: c:\gopath\src\github.com\pact-foundation\pact-go\scripts\pact.ps1

artifacts:
- path: '**\*.log'
